config/routes.rb
Rails.application.routes.draw do
root "books#index"

resources :books do
resources :comments
end

# get "/books", to: "books#index"
# get "/books/:id", to: "books#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
has_many :comments

  validates :title, presence: true
validates :author, presence: true
  validates :summary, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
@lotsabooks = Book.all
  end

def show
@book = Book.find(params[:id])
end

def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

def edit
    @book = Book.find(params[:id])
  end


def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :summary)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
    <% book.errors.full_messages_for(:author).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :summary %><br>
    <%= form.text_area :summary %><br>
    <% book.errors.full_messages_for(:summary).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Some books</h1>
<ul>
  <% @lotsabooks.each do |book| %>
    <li>
<%= link_to book.title, book %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><%= @book.author %></p>
<p><%= @book.summary %></p>

<ul>
  <li><%= link_to "Edit", edit_book_path(@book) %></li>
  <li><%= link_to "Destroy", book_path(@book), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>